services:

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    command: sh /code/entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - .:/code
      - ./data:/code/data
      - ./artifacts:/code/artifacts
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/app/v1/cyber/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      cyber_db:
        condition: service_healthy
    networks:
      - cyber_network

  cyber_db:
    container_name: cyber_db
    image: postgres:17.4-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cyber_network

  redis:
    container_name: redis
    image: redis:8.0-M04-bookworm
    restart: always
    command: /bin/sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    networks:
      - cyber_network

  frontend:
    container_name: frontend
    build:
      context: ./cyber
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./cyber:/app
      - /app/node_modules
    depends_on:
      django:
        condition: service_healthy
    environment:
      - REACT_APP_API_BASE_URL=http://django:8000/app/v1/cyber
    networks:
      - cyber_network

volumes:
  postgres_data:
  redis_data:

networks:
  cyber_network:
    driver: bridge
    name: cyber_network