# Generated by Django 5.1.7 on 2025-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=150, unique=True)),
                ('asset_type', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(max_length=100, unique=True)),
                ('criticality_level', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
